{snippet}
<div class="gridito">
    {if isset($windowOutput)}

        {* window (non javascript fallback) *}
        {block window}
        <h2>{$windowLabel}</h2>
        {!$windowOutput}
        {/block}

    {else}

        {block grid}

        {* flash messages *}
        {block flashes}
        <div n:class="gridito-flash, $flash->type === 'error' ? 'ui-state-error' : 'ui-state-highlight', ui-corner-all" n:foreach="$flashes as $flash">
            <span n:class="ui-icon, $flash->type === 'error' ? 'ui-icon-alert' : 'ui-icon-info'"></span>
            {$flash->message}
        </div>
        {/block}

        {* top toolbar *}
        {block toptoolbar}
        <div class="gridito-toolbar" n:if="$control->hasToolbar()">
            {foreach $control['toolbar']->getComponents() as $button}{control $button}{/foreach}            
            <div class="clearer"></div>
        </div>
        
        {/block}

        {* table or empty message *}
        {block data}

        {if $control->getModel()->count() > 0}

            {* grid table *}
            {block table}
            <table class="gridito-table ui-widget ui-widget-content">
                <thead>
                    <tr>
                        {block tableheader}
                        <th n:foreach="$control['columns']->getComponents() as $column" class="ui-widget-header">
                            {block tableheadercontent}
                            <span class="gridito-sorting" n:if="$column->isSortable()">
                                <a n:if="$column->getSorting() === null" n:href="sort!, $column->getName(), asc" n:class="$control->getAjaxClass()" rel="nofollow"><span class="ui-icon ui-icon-carat-2-n-s"></span></a>
                                <a n:if="$column->sorting === 'asc'" n:href="sort!, $column->getName(), desc" n:class="$control->getAjaxClass()" rel="nofollow"><span class="ui-icon ui-icon-triangle-1-n"></span></a>
                                <a n:if="$column->sorting === 'desc'" n:href="sort!, null, null" n:class="$control->getAjaxClass()" rel="nofollow"><span class="ui-icon ui-icon-triangle-1-s"></span></a>
                            </span>
                            {$column->getLabel()}
                            {/block}
                        </th>
                        <th n:if="$control->hasActions()" class="ui-widget-header"></th>
                        {/block}
                    </tr>
                </thead>
                <tbody>
                    {block tablebody}
                    <tr n:foreach="$control->getModel() as $item" n:class="$control->getRowClass($iterator, $item)">
                        <td n:class="gridito-cell, $column->getCellClass($iterator, item), $control->getHighlightOrderedColumn() && $column->getSorting() ? ui-state-highlight" n:foreach="$control['columns']->getComponents() as $column">
                            {control $column:cell $item}
                        </td>
                        <td class="gridito-actioncell" n:if="$control->hasActions()" n:inner-foreach="$control['actions']->getComponents() as $button">
                            {control $button $item}
                        </td>
                    </tr>
                    {/block}
                </tbody>
            </table>
            {/block}

        {else}
            {block emptyResult}{/block}
        {/if}

        {/block}

       	{control $control->getPaginator()}

        {/block}
    {/if}
</div>
{/snippet}