<?php

namespace Ormion\Behavior;

use Nette\Environment;
use Ormion\IRecord;

/**
 * Cached Texy
 *
 * @author Jan Marek
 * @license MIT
 */
class Texy extends \Nette\Object implements IBehavior {

    /** @var array */
    private static $texyObjects;

    /** @var string */
    private $source;

    /** @var string */
    private $name;

    /** @var string */
    private $texyClass;

    /**
     * Constructor
     * @param string name of field with generated html
     * @param string name of field with Texy source
     * @param string Texy class name
     */
    public function __construct($name, $source, $texyClass = "Texy") {
        $this->name = $name;
        $this->source = $source;
        $this->texyClass = $texyClass;
    }

    /**
     * Setup behavior
     * @param IRecord record
     */
    public function setUp(IRecord $record) {
        $record->onBeforeUpdate[] = array($this, "process");
        $record->onBeforeInsert[] = array($this, "process");
    }

    /**
     * Get Texy object
     * @param string texyClass
     * @return Texy
     */
    private function getTexy($texyClass) {
        return Environment::getService('texy');
    }

    /**
     * Get html generated by Texy
     * @param IRecord record
     * @return string
     */
    public function process(IRecord $record) {
        $texy = $this->getTexy($this->texyClass);
        $record->{$this->name} = $texy->process($record->{$this->source});
    }

}